//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cecyt13Map.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escuela
    {
        public int Cve_Escuela { get; set; }
        public string Nom_Escuela { get; set; }
        public string Piso { get; set; }
        public int Id_Ubicacion { get; set; }
    }
}
